<?php

namespace App\Jobs;

use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Barryvdh\DomPDF\Facade\Pdf;
use App\Models\Product;

class GenerateProductsPdfJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle(): void
    {
        try {
            $products = Product::with(['brand', 'categoryModel'])->orderBy('name')->get();

            $summary = [
                'total_products' => $products->count(),
                'critical' => Product::whereColumn('stock', '<', 'min_stock')->count(),
                'total_stock' => Product::sum('stock'),
                'categories' => Product::select('category')->distinct()->count(),
            ];

            $pdf = Pdf::setOptions(['isRemoteEnabled' => true, 'isHtml5ParserEnabled' => true])->loadView('products.pdf', compact('products', 'summary'));
            $output = $pdf->output();

            $path = 'public/products-report.pdf';
            Storage::put($path, $output);

            Log::info('Products PDF generated by queued job', ['path' => $path]);
        } catch (\Throwable $e) {
            Log::error('GenerateProductsPdfJob failed: '.$e->getMessage());
            throw $e;
        }
    }
}
